import fs from "fs";
const raw = JSON.parse(fs.readFileSync("scratchpad/es-dict-raw.json", "utf8"));
// 人工校正：機翻在短詞/介面詞的典型錯誤
const FIX = {
  "我的": "Yo", "記錄": "Registrar", "動態": "Actividad", "貼文": "Publicación", "儲存": "Guardar",
  "儲存中…": "Guardando…", "儲存失敗": "Error al guardar", "已追蹤": "Siguiendo", "已申請": "Solicitado",
  "確定": "OK", "關閉": "Cerrar", "清除": "Borrar", "重試": "Reintentar", "收合": "Contraer",
  "置頂": "Fijar", "已置頂到個人頁": "Fijado en tu perfil", "已取消置頂": "Desfijado", "置頂失敗": "Error al fijar",
  "檢舉": "Denunciar", "檢舉原因": "Motivo de la denuncia", "已檢舉，感謝回報": "Denunciado, gracias",
  "已檢舉並隱藏，感謝回報": "Denunciado y oculto, gracias",
  "查看": "Ver", "查看詳情": "Ver detalles", "導航": "Navegar", "查資訊": "Buscar info", "原始頁": "Página original",
  "收藏": "Guardados", "評價": "Valoración", "星級": "Estrellas",
  "日": "D", "一": "L", "二": "M", "三": "X", "四": "J", "五": "V", "六": "S",
  "陣雨": "Chubascos", "強陣雨": "Chubascos fuertes", "陣雪": "Nevadas", "強陣雪": "Nevadas fuertes",
  "半天": "Medio día", "一天": "Un día", "一天以上": "Más de un día",
  "匯出地圖包": "Exportar mapas", "匯入地圖包": "Importar mapas",
  "匯出離線地圖包": "Exportar paquete de mapas", "匯入離線地圖包": "Importar paquete de mapas",
  "神秘之卵": "Huevo Misterioso", "草叢幼蟲": "Larva de Hierba", "翩翩彩蝶": "Mariposa Bailarina",
  "靈巧山狐": "Zorro Ágil", "山林猛虎": "Tigre Montés", "初醒幼龍": "Dragón Naciente", "騰雲神龍": "Dragón de las Nubes",
  "準備": "Listo", "✋ 準備": "✋ Listo", "✓ 已準備": "✓ Listo",
  "足跡": "Rutas", "足跡地圖": "Mapa de huellas", "足跡熱力圖": "Mapa de calor",
  "記錄中": "Grabando", "小隊記錄中": "Grabación en equipo", "已暫停": "En pausa",
  "▶ 開始": "▶ Iniciar", "⏸ 暫停": "⏸ Pausa", "⏹ 結束": "⏹ Terminar", "▶ 繼續": "▶ Continuar",
  "美食": "Comida", "天氣": "Clima", "時間": "Tiempo", "步數": "Pasos",
  "免費": "Gratis", "無限": "Ilimitado", "月繳": "Mensual", "年繳": "Anual", "省 2 個月": "2 meses gratis",
  "免費試用 7 天": "Prueba gratis de 7 días", "升級 Premium": "Mejorar a Premium",
  "熱門趨勢": "Tendencias", "連線逾時": "Tiempo de conexión agotado",
  "載入中…": "Cargando…", "載入失敗": "Error al cargar", "載入更多": "Cargar más",
  "翻譯中…": "Traduciendo…", "收合翻譯": "Ocultar traducción",
  "翻譯失敗，點此重試": "Error al traducir — toca para reintentar",
  "翻譯失敗，稍後再試": "Error al traducir, inténtalo más tarde",
  "翻譯年糕": "Traducir",
  "在此步道開始記錄": "Grabar en este sendero", "預載此步道離線地圖": "Precargar mapa de este sendero",
  "下載": "Descargar", "備份與分享": "Copia y compartir", "剛剛": "Ahora mismo", "今天": "Hoy",
  "語言 Language": "Idioma",
  "一鍵下載全台離線地圖（概覽）": "Descargar mapa general de Taiwán",
  "預載所有收藏步道的離線地圖": "Precargar mapas de senderos guardados",
  "清除離線地圖": "Borrar mapas sin conexión",
  "我的足跡": "Mis estadísticas", "出行次數": "Salidas", "本月 km": "Este mes km",
  "完成步道": "Completados", "收藏步道": "Senderos guardados",
  "個人紀錄": "Récords personales", "單次最長": "Caminata más larga", "單次最大爬升": "Mayor ascenso",
  "最快平均配速": "Ritmo más rápido", "整體平均配速": "Ritmo promedio", "最常走": "Más frecuente",
  "配速趨勢": "Tendencia de ritmo", "難度分布": "Dificultad", "年度里程": "Distancia anual",
  "一週節律": "Ritmo semanal", "每月里程": "Distancia mensual", "每月卡路里消耗": "Calorías por mes",
  "我的山行回顧": "Mi año en los senderos", "趟旅程": "salidas", "公尺爬升": "m de ascenso",
  "小時": "horas", "條步道": "senderos", "座玉山": "× Yushan",
  "夥伴手冊": "Álbum del compañero", "帶我去走": "Llévame de caminata",
  "小隊同行": "Equipo en vivo", "小隊同行・我是隊長": "Equipo en vivo · Soy el líder",
  "邀請好友": "Invitar amigos", "建立小隊": "Crear equipo", "用加入碼加入": "Unirse con código",
  "設為目前": "Usar este", "退出目前小隊": "Salir del equipo", "退出目前小隊？": "¿Salir del equipo?",
  "隊友": "Compañero", "等待隊友上線…": "Esperando al equipo…",
  "編輯檔案": "Editar perfil", "我的收藏": "Mis guardados", "隱私與設定": "Privacidad y ajustes", "揪團活動": "Eventos",
  "追蹤請求": "Solicitudes de seguimiento", "同意": "Aceptar", "拒絕": "Rechazar",
  "全部標記已讀": "Marcar todo leído", "讚": "Me gusta",
  "外觀主題": "Apariencia", "淺色": "Claro", "深色": "Oscuro", "主題色": "Color de acento", "會員": "Membresía",
  "行程紀錄": "Historial", "全部路線檔": "Exportar GPX", "回顧軌跡": "Ver ruta", "路線檔": "Archivo GPX",
  "雲端備份": "Copia en la nube", "雲端還原": "Restaurar de la nube",
  "已備份到雲端 ✓": "Copiado a la nube ✓", "已自動備份到雲端 ☁️": "Copia automática hecha ☁️",
  "地形": "Terreno", "衛星": "Satélite", "暫停開放": "Cerrado temporalmente", "部分封閉": "Cierre parcial",
  "分享": "Compartir", "存成圖片": "Guardar imagen", "已存成圖片": "Imagen guardada",
  "隨手拍（記錄當下里程）": "Foto rápida (marca el km)", "省電模式": "Ahorro de batería",
  "螢幕保持喚醒": "Pantalla siempre activa", "模擬（無 GPS 預覽）": "Simular (sin GPS)",
  "隊友同行": "Equipo", "分享位置": "Compartir ubicación", "跟著路線走": "Seguir una ruta",
  "跟著這條路線走": "Seguir esta ruta",
  "準備就緒，按「開始」記錄路徑": "Listo — toca «Iniciar» para grabar",
};
const out = Object.assign({}, raw, FIX);
fs.writeFileSync("scratchpad/es-dict.json", JSON.stringify(out, null, 1));
console.log("final entries:", Object.keys(out).length, "fixes:", Object.keys(FIX).length);
